package org.eclipse.jet.exception;

import java.text.MessageFormat;

public enum JetTemplateCode implements ErrorCode {
    
	TEMPLATE_PROBLEM(201),
	COMPLIE_ERROR(202),
	INCLUDE_TEMPLATE_NOTFOUND(203),
	CONTAINS_ITS_OWN(204),
	ATTRIBUTE_VALUE_NOT_EMPTY(205),
	ATTRIBUTE_VALUE_ERROR(206),
	REQUIRE_ATTRIBUTE(207),
	OGNL_EXPRESSION_SYNTAX_EXCEPTION(208),
	OGNL_INAPPROPRIATE_EXPRESSION_EXCEPTION(209),
	OGNL_METHODFAILED_EXCEPTION(210),
	OGNL_NOSUCHPROPERTY_EXCEPTION(211),
	OGNL_NOFOUND_EXCEPTION(212),
	JET2CONTEXT_INVALID_VARIABLE_NAME(213),
	ENTITY_NOFOUND(214),
	ENTITY_TAG_NOFOUND(215),
	FIELD_NOFOUND(216),
	XML_NOFOUND(217),
	READ_CLASS_ERROR(218),
	READ_METHOD_ERROR(219),
	XPATH_ERROR(220),
	XPATH_RUNTIME_ERROR(221),
	CONTAINER_VALUE_ERROR(222)
	;
	
	private final int number;

	private JetTemplateCode(int number) {
		this.number = number;
	}

	public int getNumber() {
		return number;
	}
	
}
